#!/bin/bash
ThisScriptParentPath="$( readlink -f "${0%/*}" )"

# codediff command
#    diff tool for Visual Studio Code git diff mode

WorkingFolderPathDefault="~/_tmp/_diff/1"
if [ -e "/Applications/Visual Studio Code.app" ]; then
    VisualStudioCodePath="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
elif [ -e "${HOME}/AppData/Local/Programs/Microsoft VS Code" ]; then
    VisualStudioCodePath="${HOME}/AppData/Local/Programs/Microsoft VS Code/bin/code"
else
    VisualStudioCodePath="code"
fi
WorkingFolderPath="${WorkingFolderPathDefault}"

PositionalArgs=()
while [[ $# -gt 0 ]]; do
    case $1 in
        --test)  Options_Test="yes"; shift;;
        --merge) Options_Merge="$2"; shift; shift;;
        --check) Options_Check="yes"; shift;;
        -*) echo "Unknown option $1"; exit 1;;
        *) PositionalArgs+=("$1"); shift;;
    esac
done
set -- "${PositionalArgs[@]}"  #// set $1, $2, ...
unset PositionalArgs

#section: Main
    # : Process
    # : File
    # : String
    # : IniFile
    # : Git
    # : Others
    # : Debug
    # : Error
function  Main() {
    local  iniFilePath="$1"
    local  comparePathA="$1"  #// $1 is shared
    local  comparePathB="$2"
    local  sourcePath="$1"
    ModifyGlobalVariables
    iniFilePath="$( GetWslPathFromWindowsPath "${iniFilePath}" )"

    if [ "${comparePathA}" != "" ] && [ "${comparePathB}" != "" ]; then
        MakeIniFileFromParameters  "${comparePathA}"  "${comparePathB}"
        Diff  "${WorkingFolderPath}"

    elif [ "${Options_Merge}" == "" ]; then  #// ini file used diff
        if [ "${iniFilePath}" != "" ] && [ -f "${iniFilePath}" ]; then
            CopyIniFile  "${iniFilePath}"  "${WorkingFolderPath}"
        fi
        Diff  "${WorkingFolderPath}"

    elif [ "${sourcePath}" != "" ] && [ "${Options_Merge}" != "" ]; then
        Merge  "${sourcePath}"  "${WorkingFolderPath}"
    else
        Error  "ERROR: Unknown parameters pattern."
    fi
}

function  Diff() {
    if [ ! -e "${WorkingFolderPath}/.codediff.ini" ]; then
        rm -rf  "${WorkingFolderPath}"

        MakeWorkingFolderIfNot

        OpenIDE  "${WorkingFolderPath}"  "${WorkingFolderPath}/.codediff.ini"
        echo  ""
        echo  "Created a setting file only copied from \"${ThisScriptParentPath}/codediff_template.ini\"."
    else
        echo  "Setting file: \"${WorkingFolderPath}/.codediff.ini\""
        ParseIniFile  "${WorkingFolderPath}/.codediff.ini"  "${iniFilePath}"
        if false; then  #// if BothIsLocal 0 1; then
            CopyDiffFiles  0  "${WorkingFolderPath}/working_0"  1  "${WorkingFolderPath}/working_1"
        else
            CreateWorkingFiles  0  "${WorkingFolderPath}/working_0"
            CreateWorkingFiles  1  "${WorkingFolderPath}/working_1"
        fi
        if diff  "${WorkingFolderPath}/working_0"  "${WorkingFolderPath}/working_1" > /dev/null; then
            echo  "Same"
            return
        fi
        CreateNewGitWorking  "${WorkingFolderPath}/working_0"  "${WorkingFolderPath}/working_1"

        OpenIDE  "${WorkingFolderPath}/working"  "${WorkingFolderPath}/.codediff.ini"
        echo  ""
        echo  "You can check different by Git diff in opened VSCode source control."
    fi
}

function  Merge() {
    local  sourcePath="$1"
    local  branches="$( GetStrictCSV "${Options_Merge}" )"
    local  branch0="${branches%%,*}"  #// left of ","
    if [ "${branch0}" == "${branches}" ]; then
        local  mergingBranchesCSV=""
    else
        local  mergingBranchesCSV="${branches#*,*}"  #// right of ","
    fi
    local  mergingBranches=( )  &&  IFS=',' read -ra  mergingBranches  <<< "${mergingBranchesCSV}"
    local  errorExists="false"
    if [ "${Options_Check}" != "" ]; then
        local  runWithEcho=""
        local  redirect=/dev/null
    else
        local  runWithEcho=RunWithEcho
        local  redirect=/dev/stdout
    fi
    if IsURL "${sourcePath}"; then
        Setting_RepositoryURL+=( "${sourcePath}" )
    else
        local  localFullPath="$( readlink -f "${sourcePath}" )"
        AssertExist  "${localFullPath}"
        Setting_LocalGitWorkingFullPath+=( "${localFullPath}" )
    fi
    Setting_BranchOrTag+=("${branch0}")

    CreateWorkingFiles  0  "${WorkingFolderPath}/working"
    cd  "${WorkingFolderPath}/working"
    $runWithEcho  git config --local  rerere.enabled  false  > $redirect
    $runWithEcho  git config --local  rerere.autoupdate  false  > $redirect
    local  branch=""
    echo  "base branch: ${branch0}"
    for branch in "${mergingBranches[@]}"; do
        echo  ""  > $redirect
        echo  "incoming branch: ${branch}"
        if IsURL "${sourcePath}"; then
            mergingBranch="origin/${branch}"
        else
            mergingBranch="${branch}"
        fi
        local  mergeLogPath="${WorkingFolderPath}/_merge_${branch}.log"

        $runWithEcho \
            git merge  --no-ff --no-edit  "${mergingBranch}"  2>&1  |  \
                tee  "${mergeLogPath}"  > $redirect
        local  exitCodes="${PIPESTATUS[@]}"
        local  errorLogGuide="Log: \"${mergeLogPath}\", Working: \"${WorkingFolderPath}/working\""

        if grep "CONFLICT"  "${mergeLogPath}" > /dev/null; then
            echo -e  "${Red}CONFLICT${DefaultColor}: ${errorLogGuide}"  >&2
            errorExists="true"
        elif [ "${exitCodes}" != "0 0" ]; then
            echo -e  "${Red}ERROR${DefaultColor}: ${errorLogGuide}"  >&2
            errorExists="true"
        fi
    done

    if [ "${Options_Check}" != "" ]; then
        if [ "${errorExists}" == "true" ]; then
            return  1
        else
            echo  "No conflict"
        fi
    else
        OpenIDE  "${WorkingFolderPath}/working"
    fi
}

function  MakeWorkingFolderIfNot() {
    if [ ! -e "${WorkingFolderPath}" ]; then

        mkdir -p  "${WorkingFolderPath}"
    fi
    if [ ! -e "${WorkingFolderPath}/.codediff.ini" ]; then

        cp  "${ThisScriptParentPath}/codediff_template.ini"  "${WorkingFolderPath}/.codediff.ini"
    fi
}

function  MakeIniFileFromParameters() {
    local  parameters=( "$1" "$2" )
    local  output="${WorkingFolderPath}/.codediff.ini"
    local  fileOrFolder=1
    local  repository=2
    rm -rf    "${WorkingFolderPath}"
    mkdir -p  "${WorkingFolderPath}"

    echo  "# codediff command setting file"  >  "${output}"
    for i in {0..1}; do
        local  parameter="${parameters[${i}]}"
        local  kind=""
        echo  ""  >>  "${output}"
        echo  "[Compare-${i}]"  >>  "${output}"

        if [ "${parameter:0:4}" == "http" ]; then
            kind="${repository}"
            #// http(s)://_____
            #// http(s)://_____#__Branch__
            local  repositoryURL="${parameter%%#*}"  #// left of #
            if [ "${repositoryURL}" != "${parameter}" ]; then
                local  branchOrTag="${parameter#*#*}"  #// right of #
            else
                local  branchOrTag=""
            fi
        else
            kind="${fileOrFolder}"
            local  fullPath="$(x="$( GetFullPath "${parameter}" )" && echo "$x" || echo "(ERROR:$?)" )"
            ExitIfMatched  "${fullPath}"  '^\(ERROR:([0-9]*)\)$'
        fi

        if [ "${kind}" == "${fileOrFolder}" ]; then
            echo  "LocalPath = ${fullPath}"  >>  "${output}"
        elif [ "${kind}" == "${repository}" ]; then
            echo  "RepositoryURL = ${repositoryURL}"  >>  "${output}"
            if [ "${branchOrTag}" != "" ]; then
                echo  "BranchOrTag = ${branchOrTag}"  >>  "${output}"
            fi
        fi
    done
}

function  CopyIniFile() {
    #// Replace "LocalPath" parameter to full path.
    local  iniFilePath="$1"
    local  basePath="${iniFilePath%/*}"
    if [ "${basePath}" == "${iniFilePath}" ]; then
        basePath="."
    fi
    mkdir -p  "${WorkingFolderPath}"
    local  line=""
    local  settingIniFileLines=( )  &&  while IFS= read -r line ;do  settingIniFileLines+=("$line") ;done < "${iniFilePath}"

    for  line  in "${settingIniFileLines[@]}"; do
        local  lineType="$( ParseIniFileLineType  "${line}" )"
        if [ "${lineType}" == "parameter" ]; then
            local  name="$( ParseIniFileParameterName  "${line}" )"

            if [ "${name}" == "LocalPath" ]; then
                local  value="$( ParseIniFileParameterValue  "${line}" )"
                localPath="$( Evaluate "${value}" )"
                value="$( echo "${value}" | sed -E 's/([$^.*+?\(\){}\|[])/\\\1/g' | sed -E 's/]/\\]/g' )"  #// Escape

                localPath="$(x="$( GetFullPath  "${localPath}"  "${basePath}" )" && echo "$x" || echo "(ERROR:$?)" )"
                ExitIfMatched  "${localPath}"  '^\(ERROR:([0-9]*)\)$'
                line="$( echo "${line}"  |  sed  "s|${value}|${localPath}|" )"
            fi
        fi
        output+=("${line}")
    done

    printf '%s\n' "${output[@]}"  >  "${WorkingFolderPath}/.codediff.ini"
}

function  CreateWorkingFiles() {
    local  index="$1"
    local  outputFolderPath="$2"
    local  settingName="${Setting_Name[${index}]}"
    local  localFullPath="${Setting_LocalFullPath[${index}]}"
    local  localGitWorkingFullPath="${Setting_LocalGitWorkingFullPath[${index}]}"
    local  repositoryURL="${Setting_RepositoryURL[${index}]}"
    local  branchOrTag="${Setting_BranchOrTag[${index}]}"
    local  baseRelativePath="${Setting_BaseRelativePath[${index}]}"
    if [ "${Options_Check}" != "" ]; then
        local  runWithEcho=""
        local  redirect=/dev/null
    else
        local  runWithEcho=RunWithEcho
        local  redirect=/dev/stdout
    fi

    rm -rf  "${outputFolderPath}"  > $redirect

    if [ "${localFullPath}" != "" ]; then  #// Copy

        local  excludeOptions=""
        for  excludePath  in "${Setting_ExcludeRelativePath[@]}"; do
            excludeOptions="${excludeOptions}  --exclude \"${excludePath}\""
        done

        CopyFolder  "${localFullPath}"  "${outputFolderPath}"  ${excludeOptions}
        if [ -e "${outputFolderPath}/.git" ]; then
            mv  "${outputFolderPath}/.git"  "${outputFolderPath}/.git_"
        fi

    elif [ "${localGitWorkingFullPath}" != "" ]; then
        AssertExist  "${localGitWorkingFullPath}/.git"

        CopyFolder  "${localGitWorkingFullPath}/.git"  "${outputFolderPath}/.git"
        pushd  "${outputFolderPath}"  > /dev/null  ||  Error
        git checkout "."  > /dev/null 2>&1  ||  Error
        git checkout  "${branchOrTag}"  > /dev/null 2>&1  ||  Error
        popd  > /dev/null

    else  #// git clone. ${repositoryURL} != ""
        local  options=""
        if [ "${branchOrTag}" != "" ]; then
            options="${options}  -b ${branchOrTag}"
        fi
        if [ "${baseRelativePath}" == "." ]; then

            git clone  "${repositoryURL}" ${options}  "${outputFolderPath}"  > $redirect  ||  Error
            rm -rf  "${outputFolderPath}/.git"  > $redirect
        elif [ "${baseRelativePath:0:2}" == ".." ]; then
            Error  "ERROR: BaseRelativePath cannot be set a parent folder."
        else
            test  "$( LessThanVersion "$(git --version)" "2.26.0" )"  == "${False}"  ||  Error  "ERROR: Requires git 2.26.0 or higher"
            git clone  --filter=blob:none --sparse  "${repositoryURL}" ${options} \
                "${WorkingFolderPathDefault}/workingOfWorking"  > $redirect  ||  Error
            pushd  "${WorkingFolderPathDefault}/workingOfWorking"  > /dev/null  ||  Error

            git sparse-checkout set "${baseRelativePath}"  > $redirect
            popd  > /dev/null
            rm -rf  "${outputFolderPath}"

            mv  "${WorkingFolderPathDefault}/workingOfWorking/${baseRelativePath}"  "${outputFolderPath}"
            rm -rf  "${WorkingFolderPathDefault}/workingOfWorking"
        fi

        local  deletingPath=""
        for  deletingPath  in "${Setting_ExcludeRelativePath[@]}"; do
            pushd  "${outputFolderPath}"  > /dev/null  ||  Error

            rm -rf  "${deletingPath}"
            popd  > /dev/null
        done
    fi
}

function  BothIsLocal() {
    local  indexA="$1"
    local  indexB="$2"
    local  localFullPathA="${Setting_LocalFullPath[${indexA}]}"
    local  localFullPathB="${Setting_LocalFullPath[${indexB}]}"

    if [ "${localFullPathA}" != "" ] && [ "${localFullPathB}" != "" ]; then
        return  0  #// true
    else
        return  1  #// false
    fi
}

function  CopyDiffFiles() {
    local  indexA="$1"
    local  outputFolderPathA="$2"
    local  indexB="$3"
    local  outputFolderPathB="$4"
    local  folderPathA="${Setting_LocalFullPath[${indexA}]}"
    local  folderPathB="${Setting_LocalFullPath[${indexB}]}"
    local  filePath

    mkdir -p  "${folderPathA}"
    mkdir -p  "${folderPathB}"
    local  diffFilePaths="$( GetDiffFilePaths "${folderPathA}"  "${folderPathB}" )"
    while IFS= read -r filePath; do  #// filePath=( read file in "diffFilePaths" )
        local  sourceFilePathA="${folderPathA}/${filePath}"
        local  sourceFilePathB="${folderPathB}/${filePath}"
        local  destinationFilePathA="${outputFolderPathA}/${filePath}"
        local  destinationFilePathB="${outputFolderPathB}/${filePath}"
        if [ -e "${sourceFilePathA}" ]; then
            mkdir -p  "${destinationFilePathA%/*}"  #// left of last "/"

            cp -ap "${sourceFilePathA}"  "${destinationFilePathA}"
        fi
        if [ -e "${sourceFilePathB}" ]; then
            mkdir -p  "${destinationFilePathB%/*}"  #// left of last "/"

            cp -ap "${sourceFilePathB}"  "${destinationFilePathB}"
        fi
    done < <( echo "${diffFilePaths}" )
}

function  GetDiffFilePaths() {
    local  folderPathA="$1"
    local  folderPathB="$2"

    diff -rq  "${folderPathA}"  "${folderPathB}"  |  DiffFilesFilter  "${folderPathA}"  "${folderPathB}"
}

function  DiffFilesFilter() {
    #// Input:
    #//     Files __PathA__ __PathB__ differs
    #//     Only in __FolderPath__: __FileName__
    #// Output:
    #//     __RelativeFileOrFolderPath__
    #//     __RelativeFileOrFolderPath__
    local  standardOutput="$( cat )"  #// function stdin
    local  folderPathA="$1"
    local  folderPathB="$2"

    local  simpleOutput="$( echo  "${standardOutput}"  |  sed -E  's|^Files (.+) and .+ differ$|\1|' )"
    local  simpleOutput="$( echo  "${simpleOutput}"    |  sed -E  's|Only in (.+): (.+)|\1/\2|' )"
    local  simpleOutput="$( echo  "${simpleOutput}"    |  sed -E  "s|^${folderPathA}/||" )"
    local  simpleOutput="$( echo  "${simpleOutput}"    |  sed -E  "s|^${folderPathB}/||" )"

    echo  "${simpleOutput}"
}

function  CreateNewGitWorking() {
    local  oldContentsPath="$1"
    local  newContentsPath="$2"
    AssertNotExist  "${oldContentsPath}/.git"
    AssertNotExist  "${newContentsPath}/.git"
    local  gitLogPath="${WorkingFolderPath}/_git.log"

    rm -rf "${WorkingFolderPath}/working"
    mkdir  "${WorkingFolderPath}/working"
    pushd  "${WorkingFolderPath}/working"  > /dev/null  ||  Error

    git init ${GitInitOption}  > /dev/null  2>&1  ||  Error
    git config --local user.email "you@example.com"
    git config --local user.name "Your Name"
    popd  > /dev/null
    mv  "${WorkingFolderPath}/working/.git"  "${oldContentsPath}"  ||  Error
    pushd  "${oldContentsPath}"  > /dev/null  ||  Error
    SetReadOnly  "."
    SetNotReadOnly  ".git"

    git add "."
    git commit -m "${Setting_Name[0]}"  > "${gitLogPath}"  2>&1  ||  Error  "ERROR: Failed git commit in \"${PWD}\". git output: $( cat "${gitLogPath}" )"
    rm  "${gitLogPath}"
    popd  > /dev/null
    mv  "${oldContentsPath}/.git"  "${newContentsPath}"  ||  Error
    pushd  "${newContentsPath}"  > /dev/null  ||  Error
    SetReadOnly  "."
    SetNotReadOnly  ".git"

    git add "."
    git commit -m "${Setting_Name[1]}"  > "${gitLogPath}"  2>&1  ||  Error  "ERROR: Failed git commit in \"${PWD}\". git output: $( cat "${gitLogPath}" )"
    rm  "${gitLogPath}"
    popd  > /dev/null
    mv  "${newContentsPath}/.git"  "${WorkingFolderPath}/working"  ||  Error
    pushd  "${WorkingFolderPath}/working"  > /dev/null  ||  Error

    git checkout "."  > /dev/null  2>&1  ||  Error
    git reset --soft HEAD^  ||  Error
    SetReadOnly  "."
    SetNotReadOnly  ".git"
    popd  > /dev/null
}

function  OpenIDE() {
    local  openingFolderPath="$1"
    local  secondPath="$2"
    openingFolderPath="$( GetWindowsPathFromWslPath "${openingFolderPath}" )"
    secondPath="$( GetWindowsPathFromWslPath "${secondPath}" )"
    if [ "${Options_Test}" != "" ]; then
        echo  "OpenIDE \"${openingFolderPath}\""  >  "_codediff.log"
    else
        echo  "codediff: \"${openingFolderPath}\""

        "${VisualStudioCodePath}" -g  "${openingFolderPath}"  "${secondPath}"
    fi
}

function  ParseIniFile() {
    local  iniFilePath="$1"
    local  iniFileSourcePath="$2"  #// "" or path. It is necessary to specify in the case that iniFilePath is copy destination.
    ResetSetting
    StartTagParser  "${iniFilePath}"
    local  basePath="${iniFilePath%/*}"
    local  settingName=""
    local  localFullPath=""
    local  repositoryURL=""
    local  branchOrTag=""
    local  baseRelativePath=""
    AssertExist  "${iniFilePath}"
    local  line=""
    local  settingIniFileLines=( )  &&  while IFS= read -r line ;do  settingIniFileLines+=("$line") ;done < "${iniFilePath}"

    for  line  in "${settingIniFileLines[@]}"; do
        if ! ParsingIsActive "${line}"; then  continue  ;fi
        local  lineType="$( ParseIniFileLineType  "${line}" )"

        if [ "${lineType}" == "section" ]; then
            if [ "${settingName}" != "" ]; then
                AppendSetting  "${settingName}"  "${localFullPath}"  "${repositoryURL}"  "${branchOrTag}"  "${baseRelativePath}"  "${iniFileSourcePath}"
            fi

            settingName="$( ParseIniFileSectionName "${line}" )"
            localFullPath=""
            repositoryURL=""
            branchOrTag=""
            baseRelativePath=""
        elif [ "${lineType}" == "parameter" ]; then
            local  name="$( ParseIniFileParameterName  "${line}" )"
            local  value="$( ParseIniFileParameterValue  "${line}" )"
            value="$( Evaluate "${value}" )"
            if [ "${name}" == "LocalPath" ]; then
                localFullPath="$( GetFullPath  "${value}"  "${basePath}" )"
            elif [ "${name}" == "RepositoryURL" ]; then
                repositoryURL="${value}"
            elif [ "${name}" == "BranchOrTag" ]; then
                branchOrTag="${value}"
            elif [ "${name}" == "BaseRelativePath" ]; then
                baseRelativePath="${value}"
            elif [ "${name}" == "ExcludeRelativePath" ]; then
                Setting_ExcludeRelativePath+=("${value}")
            else
                Error  "ERROR: Unknown parameter: ${name} in \"${iniFilePath}\"."
            fi
        fi
    done
    AppendSetting  "${settingName}"  "${localFullPath}"  "${repositoryURL}"  "${branchOrTag}"  "${baseRelativePath}"  "${iniFileSourcePath}"

    if [ "${#Setting_Name[@]}" != 2 ]; then
        Error  "ERROR: section count must be 2 in ${WorkingFolderPath}/.codediff.ini file."
    fi
}

function  ResetSetting() {
    Setting_Name=( )
    Setting_LocalFullPath=( )
    Setting_RepositoryURL=( )
    Setting_BranchOrTag=( )
    Setting_BaseRelativePath=( )
    Setting_ExcludeRelativePath=( )
}

function  AppendSetting() {
    local  settingName="$1"
    local  localFullPath="$2"
    local  repositoryURL="$3"
    local  branchOrTag="$4"
    local  baseRelativePath="$5"
    local  iniFileSourcePath="$6"
    if [ "${iniFileSourcePath}" == "" ]; then
        local  lastOfErrorMessage="in ${WorkingFolderPath}/.codediff.ini file."
    else
        local  lastOfErrorMessage="in ${iniFileSourcePath} file."
    fi

    if [ "${settingName}" == "" ]; then
        Error  "ERROR: Not specified section name ${lastOfErrorMessage}"
    elif [ "${localFullPath}" != "" ]; then
        if [ "${localFullPath:0:1}" != "/" ]; then
            Error  "ERROR: LocalPath must be full path ${lastOfErrorMessage}"
        elif [ "${repositoryURL}" != "" ]; then
            Error  "ERROR: Cannot both setting LocalPath and RepositoryURL ${lastOfErrorMessage}"
        elif [ "${branchOrTag}" != "" ]; then
            Error  "ERROR: Cannot both setting LocalPath and BranchOrTag ${lastOfErrorMessage}"
        elif [ "${baseRelativePath}" != "" ]; then
            Error  "ERROR: Cannot both setting LocalPath and BaseRelativePath ${lastOfErrorMessage}"
        fi
    elif [ "${repositoryURL}" != "" ]; then
        if [ "${baseRelativePath}" == "" ]; then
            baseRelativePath="."
        fi
    else
        Error  "ERROR: LocalPath or RepositoryURL must be set ${lastOfErrorMessage}"
    fi

    Setting_Name+=("${settingName}")
    Setting_LocalFullPath+=("${localFullPath}")
    Setting_RepositoryURL+=("${repositoryURL}")
    Setting_BranchOrTag+=("${branchOrTag}")
    Setting_BaseRelativePath+=("${baseRelativePath}")
}

function  StartTagParser() {
    local  iniFilePath="$1"

    if cat "${iniFilePath}"  |  grep "#codediff:" > /dev/null; then
        TagParserIsActive="${True}"
        ParsingState="NotStart"
        SettingIndent=""
    else
        TagParserIsActive="${False}"
    fi
}
TagParserIsActive="${False}"
ParsingState="NotStart"
SettingIndent=""

function  ParsingIsActive() {
    local  line="$1"
    if [ "${TagParserIsActive}" == "${False}" ]; then
        return  "${True}"
    fi

    if [ "${line/[[:space:]]/}" != "" ]; then
        if [ "${ParsingState}" == "NotStart" ]; then
            if echo "${line}"  |  grep "#codediff:" > /dev/null; then
                ParsingState="OnTag"
            fi
        elif [ "${ParsingState}" == "OnTag" ]; then
            SettingIndent="$( echo "${line}"  |  grep -o "^ *" )"
            ParsingState="Active"
        elif [ "${ParsingState}" == "Active" ]; then
            if !( echo "${line}"  |  grep "^${SettingIndent}" ) > /dev/null; then
                ParsingState="Done"
            fi
        fi
    fi

    if [ "${ParsingState}" == "Active" ]; then
        return  "${True}"
    else
        return  "${False}"
    fi
}

function  IsWindowsFile() {  #// Shared file with Windows in Linux process
    local  filePath="$1"
    if [ -d "${filePath}" ]; then Error ;fi
    if df -h "${filePath}"  |  grep -E '/dev/' > /dev/null; then  #// Linux file system
        return "${False}"  #// Linux file
    else
        return "${True}"  #// Windows file
    fi
}

function  SetReadOnly() {
    SetReadOnlyOrNot --set-read-only  "$@"
}

function  SetNotReadOnly() {
    SetReadOnlyOrNot --set-not-read-only  "$@"
}

if [ "${READ_ONLY_CHMOD}" == "" ]; then
    READ_ONLY_CHMOD="a-w"   #// For Linux only
fi
if [ "${NOT_READ_ONLY_CHMOD}" == "" ]; then
    NOT_READ_ONLY_CHMOD="u+w"   #// For Linux only
fi

function  SetReadOnlyOrNot() {
    local  operation="$1"
    local  fileOrFolderPath="$2"

    if [ -f "${fileOrFolderPath}" ]; then
        local  filePath="${fileOrFolderPath}"
        if [ "${operation}" == "--set-read-only" ]; then
            if IsWindowsFile "${filePath}"; then

                chmod 444  "${filePath}"
            else
                chmod ${READ_ONLY_CHMOD}  "${filePath}"
            fi
        elif [ "${operation}" == "--set-not-read-only" ]; then
            if IsWindowsFile "${filePath}"; then

                chmod 777  "${filePath}"
            else
                chmod ${NOT_READ_ONLY_CHMOD}  "${filePath}"
            fi
        fi

    elif [ -d "${fileOrFolderPath}" ]; then
        local  folderPath="${fileOrFolderPath}"
        local  filePaths="$( find "${folderPath}"  -type f )"
        local  firstFilePath="$( echo  "${filePaths}"  |  head -1 )"
        if [ "${firstFilePath}" != "" ]; then
            if [ "${operation}" == "--set-read-only" ]; then
                if IsWindowsFile "${firstFilePath}"; then
                    echo  "${filePaths}"  |  xargs -I{} chmod 444 "{}"
                else
                    echo  "${filePaths}"  |  xargs -I{} chmod ${READ_ONLY_CHMOD} "{}"
                fi
            elif [ "${operation}" == "--set-not-read-only" ]; then
                if IsWindowsFile "${firstFilePath}"; then

                    echo  "${filePaths}"  |  xargs -I{} chmod 777 "{}"
                else
                    echo  "${filePaths}"  |  xargs -I{} chmod ${NOT_READ_ONLY_CHMOD} "{}"
                fi
            fi
        fi
    fi
}

#section: Process

function  RunWithEcho() {
    local  optionsText=""
    if [ "${1:0:13}" == "--output-sed=" ]; then
        local  sedParameters="${1:13}"  #// Use \s instead of space
        optionsText="${optionsText}--output-sed=____ "
        shift
    else
        sedParameters=""
    fi
    if [ "${optionsText}" != "" ]; then
        optionsText="$ ${optionsText}"
    fi

    echo  "$ cd  \"${PWD}\""
    if [ "${sedParameters}" == "" ]; then
        echo  "${optionsText}$ $( GetArgumentsString "$@" )"  >&2
    else
        echo  "${optionsText}$ $( GetArgumentsString "$@" )"  |  sed -E "${sedParameters}"  >&2
    fi

    "$@"
}

function  GetArgumentsString() {
    local  arguments=""

    for argument in "$@"; do
        if [ "${argument:0:1}" == "-" ]; then
            arguments="${arguments} ${argument}"
        elif [ "${argument}" == ""  -o  "${argument}" == "&&"  -o  "${argument}" == "||" ]; then
            arguments="${arguments} \"${argument}\""
        elif [ "$( echo "${argument}" | sed -E 's- |\.|/--' )" != "${argument}" ]; then  #// has space, period or slash
            arguments="${arguments} \"${argument}\""
        else
            arguments="${arguments} ${argument}"
        fi
    done

    echo  "${arguments:1}"
}

#section: File

function  CopyFolder() {
    local  source="$1"
    local  destination="$2"
    local  option="$3"
    local  excludePaths=( )
    while true; do
        option="$3"
        if [ "${option}" == "" ]; then
            break
        fi
        if [ "${option}" == "--exclude" ]; then
            excludePaths+=( "$( CutDoubleQuotation "$4" )" )
            shift  2
        elif [ "${option:0:10}" == "--exclude=" ]; then
            excludePaths+=("${option:10}")
            shift
        else
            Error  "Not supported option: ${ignoreDotGit}"
        fi
    done
    source="$( CutLastOf  "${source}"  "/" )"
    destination="$( CutLastOf  "${destination}"  "/" )"

    mkdir -p  "${destination}/"
    if [ "${#excludePaths[@]}" == 0 ]; then

        ls -a "${source}" | grep -v  -e "^\.$"  -e "^\.\.$" | xargs  -I {} \
            cp -Rap  "${source}/{}"  "${destination}/"
    else
        local  sourceEscaped="$( echo "${source}" | sed -E 's/([$^.*+?\(\){}\|[])/\\\1/g' | sed -E 's/]/\\]/g' )"
        local  sourceFilePathText="$( find "${source}" -type f  |  sort )"
        local  sourceEmptyFolderPathText="$( ScanEmptyFolderPaths  "${source}"  "${sourceFilePathText}" )"
        local  filePathText="$( echo "${sourceFilePathText}"  |  sed -E "s|^${sourceEscaped}|.|" )"
        local  emptyFolderPathText="$( echo "${sourceEmptyFolderPathText}"  |  sed -E "s|^${sourceEscaped}|.|" )"
        local  excludePath=""
        for excludePath in "${excludePaths[@]}"; do
            if [ "${excludePath:0:2}" != "./" ]; then
                excludePath="./${excludePath}"
            fi
            local  excludePathEscaped="$( echo "${excludePath}" | sed -E 's/([$^.*+?\(\){}\|[])/\\\1/g' | sed -E 's/]/\\]/g' )"

            filePathText="$( echo "${filePathText}"  |  grep -vE "^${excludePathEscaped}" )"
            emptyFolderPathText="$( echo "${emptyFolderPathText}"  |  grep -vE "^${excludePathEscaped}" )"
        done
        local  fileFolderPathText="$( echo "${filePathText}"  |  sed -E 's|/[^/]*$||'  |  uniq )"

        echo  "${emptyFolderPathText}"  |  xargs  -I {} \
            mkdir -p  "${destination}/{}"
        echo  "${fileFolderPathText}"  |  xargs  -I {} \
            mkdir -p  "${destination}/{}"
        echo  "${filePathText}"  |  xargs  -I {} \
            cp -Rap  "${source}/{}"  "${destination}/{}"
    fi
}

function  ScanEmptyFolderPaths() {
    local  basePath="$1"
    local  scanedFilePaths="$2"

    local  folderPaths="$( find "${basePath}" -type d  |  sort  |  sed -E "s|$|:|"  |  sed -E "s|^|:|" )"
    local  fileFolderPaths="$( echo "${scanedFilePaths}"  |  sed -E 's|/[^/]*$|:|'  |  sed -E "s|^|:|"  |  uniq )"
    local  emptyFolderPaths="$( grep -vFf <(echo "${fileFolderPaths}")  <(echo "${folderPaths}")  | \
        sed -E 's/:$//'  |  sed -E 's/^://' )"

    echo  "${emptyFolderPaths}"
}

function  GetFullPath() {
    local  relativePath="$1"  #// or full path
    local  basePath="$2"
    local  option="$3"
    if [ "${option}" == "--touch" ]; then
        if [ "${basePath}" == "" ]; then
            mkdir -p  "${relativePath%/*}"
            touch  "${relativePath}"  #// for next readlink
        else
            local  touchPath="${basePath}/${relativePath}"
            mkdir -p  "${touchPath%/*}"
            touch  "${basePath}/${relativePath}"  #// for next readlink
        fi
    fi

    if [ "${basePath}" == "" ]; then
        local  fullPath="$( readlink -f  "${relativePath}" )"
        if [ "${fullPath}" != "" ]; then
            echo  "${fullPath}"
            return
        fi
        basePath="${PWD}"
    fi
    local  baseTail="${basePath: $((${#basePath}-3))}"
    if [ "${baseTail}" == "/.." ]; then
        basePath=${basePath%/*}
        basePath=${basePath%/*}
    fi
    local  isFullPath="false"
    if [ "${relativePath:0:1}" == "/" ] || [ "${relativePath:0:1}" == "$" ]; then
        isFullPath="true"
    elif [ "${relativePath:0:3}" == 'c:/' ] || [ "${relativePath:0:3}" == 'c:\' ] || [ "${relativePath:0:3}" == 'C:/' ] || [ "${relativePath:0:3}" == 'C:\' ]; then
        isFullPath="true"
    fi

    if [ "${isFullPath}" == "true" ]; then
        local  fullPath="${relativePath}"
    else
        local  fullPath="$( readlink -f  "${basePath}/${relativePath}" )"
    fi
    fullPath="$( eval echo "${fullPath}" )"  #// Evaluate variables
    if [ "${fullPath}" == "" ]; then
        if [ "${option}" == "--mkdir" ]; then
            pushd  "${basePath}"  > /dev/null
            mkdir -p  "${relativePath}"
            popd  > /dev/null
        elif [ "${option}" != "--empty-if-not-exist" ]; then
            Error  "ERROR: Cannot get full path from \"${relativePath}\" in \"${basePath}\"."
        fi
    fi
    echo  "${fullPath}"
}

function  IsURL() {
    echo  "$1"  |  grep -E "^[a-z]+://"  > /dev/null
}

function  AssertExist() {
    local  path="$1"
    local  leftOfWildcard="${path%\**}"
    if [ "${leftOfWildcard}" == "${path}" ]; then  #// No wildcard

        if [ ! -e "${path}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    else
        local  rightOfWildcard="${path##*\*}"
        if [ ! -e "${leftOfWildcard}"*"${rightOfWildcard}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    fi
}

function  AssertNotExist() {
    local  path="$1"

    if [ -e "${path}" ]; then
        Error  "ERROR: Found \"${path}\""
    fi
}

#section: String

function  GetStrictCSV() {
    #// This version does not support comma-containing values
    echo "$1" | sed 's/ *, */,/g'
}

function  CutLastOf() {
    local  wholeString="$1"
    local  lastExpected="$2"

    if [ "${wholeString:${#wholeString}-${#lastExpected}:${#lastExpected}}" == "${lastExpected}" ]; then
        echo  "${wholeString:0:${#wholeString}-${#lastExpected}}"
    else
        echo  "${wholeString}"
    fi
}

function  CutDoubleQuotation() {
    echo  "$1"  |  sed -E 's/^"|"$//g'
}

#section: IniFile

function  ParseIniFileLineType() {
    local  line="$1"
    local  words=$( echo "${line}" | xargs )
    local  head="${words:0:1}"

    if [ "${head}" == ""  -o  "${head}" == ";"  -o  "${head}" == "#" ]; then
        echo  "empty"
    elif [ "${head}" == "[" ]; then
        echo  "section"
    elif  echo "${line}" | grep '=' > /dev/null; then
        echo  "parameter"
    else
        echo  "unknown"
    fi
}

function  ParseIniFileSectionName() {
    local  line="$1"
    echo  "${line}"  |  sed -E 's/^[ \t]*\[|\] *$//g'
}

function  ParseIniFileParameterName() {
    local  line="$1"
    echo  "${line}"  |  grep -o  '[^ ]* *='  |  sed 's/ *=$//'
}

function  ParseIniFileParameterValue() {
    local  line="$1"
    local  quotedValue="$( echo "${line}"  |  grep -o  '".*"' )"
    if [ "${quotedValue}" != "" ]; then
        echo  "${quotedValue: 1 : $(( ${#quotedValue} - 2 ))}"  #// Cut " "
    else
        echo  "${line}"  |  grep -o '=.*'  |  sed -E 's/^= *//g'  
    fi
}

#section: Git

function  gitInitOption() {
    if [ "$( LessThanVersion "$(git --version)" "2.31.1" )" == "${True}" ]; then
        echo  ""
    else
        echo  "-bmain"  #// "-b main" occurs an error in bash debug
    fi
}

#section: Others

function  LessThanVersion() {
    # LessThanVersion
    #     if [ "$( LessThanVersion "$(git --version)" "2.31.1")" == "${True}" ]; then
    local  textContainsVersionA="$1"
    local  textContainsVersionB="$2"
    local  isGoodFormat="${True}"
    echo "${textContainsVersionA}" | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+" > /dev/null  ||  isGoodFormat="${False}"
    echo "${textContainsVersionB}" | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+" > /dev/null  ||  isGoodFormat="${False}"
    if [ "${isGoodFormat}" == "${False}" ]; then
        Error  "\"${textContainsVersionA}\" or \"${textContainsVersionB}\" is not semantic version."
    fi

    local  numbersA=( $( echo "${textContainsVersionA}" | grep -o -e "[0-9]\+" ) )
    local  numbersB=( $( echo "${textContainsVersionB}" | grep -o -e "[0-9]\+" ) )
    if [ "${numbersA[0]}" -lt "${numbersB[0]}" ]; then
        echo "${True}"
        return
    elif [ "${numbersA[0]}" == "${numbersB[0]}" ]; then
        if [ "${numbersA[1]}" -lt "${numbersB[1]}" ]; then
            echo "${True}"
            return
        elif [ "${numbersA[1]}" == "${numbersB[1]}" ]; then
            if [ "${numbersA[2]}" -lt "${numbersB[2]}" ]; then
                echo "${True}"
                return
            fi
        fi
    fi
    echo "${False}"
}

function  Evaluate() {
    # Evaluate
    #     Expand variables
    # Example:
    #     var1='value  1'
    #     var2='${var1}  2'
    #     evaluated="$( Evaluate "${var2}" )"  #// value  1  2
    local  expression="$1"
    eval echo "$( eval echo '\""${expression}"\"' )"
}

function  GetWslPathFromWindowsPath() {
    local  windowsPath="$1"
    local  windowsSlashPath="$( echo "${windowsPath}" | sed 's/\\/\//g' )"

    if [ "${windowsSlashPath:0:3}" == "C:/" ] || [ "${windowsSlashPath:0:3}" == "c:/" ] && [ "${WslMnt}" != "" ]; then
        echo  "${WslMnt}/c/${windowsSlashPath:3}"
    elif [ "${windowsSlashPath:0:3}" == "/c/" ] && [ "${WslMnt}" != "" ]; then
        echo  "${WslMnt}${windowsSlashPath}"
    else
        echo  "${windowsSlashPath}"
    fi
}

function  GetWindowsPathFromWslPath() {
    local  wslPath="$1"

    if [ "${WslMnt}" != "" ] && [ "${wslPath:0:7}" == "${WslMnt}/c/" ] ; then
        echo  "C:${wslPath:6}"
    else
        echo  "${wslPath}"
    fi
}

function  AssertExist() {
    local  path="$1"
    local  leftOfWildcard="${path%\**}"
    if [ "${leftOfWildcard}" == "${path}" ]; then  #// No wildcard

        if [ ! -e "${path}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    else
        local  rightOfWildcard="${path##*\*}"
        if [ ! -e "${leftOfWildcard}"*"${rightOfWildcard}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    fi
}

function  AssertNotExist() {
    local  path="$1"

    if [ -e "${path}" ]; then
        Error  "ERROR: Found \"${path}\""
    fi
}

#section: Debug

function  pp() {
    # pp
    #     Debug print
    # Example:
    #     pp "$config"
    #     pp "$config" config
    #     pp "$array" array  ${#array[@]}  "${array[@]}"
    #     pp "123"
    #     $( pp "$config" >&2 )
    local  value="${1-""}"  #// "${1-""}" means that "$1" default is "".
    local  variableName="${2-""}"  #// "${1-""}" means that "$1" default is "".
    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi  #// Add spaces
    local  oldIFS="$IFS"
    IFS=$'\n'
    local  valueLines=( ${value} )
    IFS="$oldIFS"

    local  type=""
    if [ "${variableName}" != "" ]; then
        if [[ "$(declare -p ${variableName} 2>&1 )" =~ "declare -a" ]]; then
            local  type="array"
        fi
    fi
    if [ "${type}" == "" ]; then
        if [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
            local  type="oneLine"
        else
            local  type="multiLine"
        fi
    fi

    if [[ "${type}" == "oneLine" ]]; then
        echo  "@@@${variableName}= \"${value}\" -------- $( GetCodePosition 1 ) ---------------------------"  >&2
    elif [[ "${type}" == "multiLine" ]]; then
        echo  "@@@${variableName} -------- $( GetCodePosition 1 ) ---------------------------"  >&2
        echo  "\"${value}\"" >&2
    elif [[ "${type}" == "array" ]]; then
        echo  "@@@${variableName} -------- $( GetCodePosition 1 ) ---------------------------"  >&2
        local  count="${3-""}"  #// "${1-""}" means that "$1" default is "".
        if [ "${count}" == "" ]; then
            echo  "[0]: \"$4\""  >&2
            echo  "[1]: ERROR: pp parameter is too few"  >&2
        elif [ "${count}" == "0" ]; then
            echo  "[]"  >&2
        else
            local  i=""
            for (( i = 0; i < ${count}; i += 1 ));do
                echo  "[${i}]: \"$4\""  >&2
                shift
            done
        fi
    else
        echo  "@@@${variableName}? -------- $( GetCodePosition 1 ) ---------------------------"  >&2
    fi
}

function  GetCodePosition() {
    local  parent="${1-"0"}"  #// "${1-"0"}" means that "$1" default is "0".
    local  frame=( $( caller "${parent}" ) )
    local  fileName="${frame[2]}"
    local  lineNum="${frame[0]}"
    echo  "${fileName}:${lineNum}"
}

function  PrintCallStack() {
    echo  "Call stack:"  >&2
    local  index=0
    local  frame
    while frame=( $( caller "${index}" ) ); do
        local  functionName="${frame[1]}"
        local  fileName="${frame[2]}"
        local  lineNum="${frame[0]}"
        echo  "    ${functionName} (${fileName}:${lineNum})"  >&2
        (( index += 1 ))  ||  true
    done
}

#section: Error

function  ExitIfMatched() {
    # ExitIfMatched
    #     Check function return code or function exit code in $( )
    # Example:
    #     local  out="$(x="$( command )" && echo "$x" || echo "(ERROR:$?)" )"
    #     ExitIfMatched  "${out}"  '^\(ERROR:([0-9]*)\)$'
    local  output="$1"
    local  regularExpression="$2"

    if [[ "${output}" =~ ${regularExpression} ]]; then
        local  exitCode="$( echo "${output}"  |  sed -E  's/'"${regularExpression}"'/\1/')"
        exit  "${exitCode}"
    fi
}

function  Error() {
    local  errorMessage="${1-""}"  #// "${1-""}" means that "$1" default is "".
    local  exitCode="${2-""}"      #// "${1-""}" means that "$1" default is "".
    if [ "${errorMessage}" == "" ]; then
        errorMessage="ERROR"
    fi
    if [ "${exitCode}" == "" ]; then  exitCode=2  ;fi
    if [ "${InChildProcess}" == "yes" ]; then
        local  seeChildProcessMessage="(See above error message. The following message is usually no effective.) "
    else
        local  seeChildProcessMessage=""
    fi

    PrintCallStack

    echo -e  "${seeChildProcessMessage}${errorMessage}"  >&2
    if [ "${MSYSTEM}" == "MINGW64" ]; then
        echo  "[Advice] Git bash is flaky on Windows. Install WSL2 and input the command: wsl __CommadAndParameters__"
    fi
    exit  "${exitCode}"
}

function  ModifyGlobalVariables() {

    #// Set default values. "! -v" means that variable is not defined.
    if ! [[ -v http_proxy ]]; then  http_proxy=""  ;fi
    if ! [[ -v https_proxy ]]; then  https_proxy=""  ;fi
    if ! [[ -v no_proxy ]]; then  no_proxy=""  ;fi
    if ! [[ -v HTTP_PROXY ]]; then  __VariHTTP_PROXYableName__=""  ;fi
    if ! [[ -v HTTPS_PROXY ]]; then  HTTPS_PROXY=""  ;fi
    if ! [[ -v NO_PROXY ]]; then  NO_PROXY=""  ;fi
    echo  "http_proxy = ${http_proxy}"
    echo  "https_proxy = ${https_proxy}"
    echo  "no_proxy = '${no_proxy}'"
    echo  "HTTP_PROXY = ${HTTP_PROXY}"
    echo  "HTTPS_PROXY = ${HTTPS_PROXY}"
    echo  "NO_PROXY = '${NO_PROXY}'"

    #// USER, USERNAME, HOME, USERPROFILE, ProgramFiles = ...
    if [ -e "/c/Windows" ]; then  #// if Windows Git bash
        ScriptEnvironment="Windows"
        export USER="${USERNAME}"
        export USERPROFILE="${HOME}"
        export HOME2="${USERPROFILE}"
        export ProgramFiles="/c/Program Files"
    elif [  -e "/mnt/c/" ] && [ "${PWD:0:7}" == "/mnt/c/" ]; then  #// if Linux on WSL2
        ScriptEnvironment="Linux"
        if ! [[ -v USERNAME ]]; then  #// If USERNAME was not defined in parent script  #// "! -v" means that variable is not defined.
            export USERNAME="$( /mnt/c/WINDOWS/system32/cmd.exe /c 'echo %USERNAME%'  2> /dev/null )"
            export USERNAME="${USERNAME:0:${#USERNAME}-1}"  #// Cut last CR
        fi
        export USERPROFILE="/mnt/c/Users/${USERNAME}"
        export HOME2="${USERPROFILE}"
        export ProgramFiles="/mnt/c/Program Files"
    else  #// if Linux
        ScriptEnvironment="Linux"
        export USERNAME="${USER}"
        export USERPROFILE=""
        export HOME2="${HOME}"
        export ProgramFiles=""
    fi
    if [ "${ScriptEnvironment}" == "Linux" ]; then
        if [ "${USER}" == "root" ]; then
            ScriptEnvironment="LinuxRoot"
        else
            ScriptEnvironment="LinuxUser"
        fi
    fi
    if [ "${PWD:0:7}" == "/mnt/c/" ]; then
        WslMnt="/mnt"
    fi

    #// Expand ~
    WorkingFolderPathDefault="$( echo "${WorkingFolderPathDefault}"  |  sed -E "s|^~|${HOME2}|" )"
    WorkingFolderPath="$( echo "${WorkingFolderPath}"  |  sed -E "s|^~|${HOME2}|" )"
}

True=0
False=1
DefaultColor="\e[0m"
Red="\e[91m"
GitInitOption=$(gitInitOption)
Setting_Name=( )
Setting_LocalFullPath=( )
Setting_RepositoryURL=( )
Setting_BranchOrTag=( )
Setting_BaseRelativePath=( )
Setting_ExcludeRelativePath=( )

Main "$@"
