#!/bin/bash
ThisScriptParentPath="$( readlink -f "${0%/*}" )"

# codediff command
#    diff tool for Visual Studio Code git diff mode

WorkingFolderPathDefault="$HOME/_tmp/_diff/1"
if [ -e "/Applications/Visual Studio Code.app" ]; then
    VisualStudioCodePath="/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
elif [ -e "${HOME}/AppData/Local/Programs/Microsoft VS Code" ]; then
    VisualStudioCodePath="${HOME}/AppData/Local/Programs/Microsoft VS Code/bin/code"
else
    VisualStudioCodePath="__NotFoundVisualStudioCode"
fi

PositionalArgs=()
while [[ $# -gt 0 ]]; do
    case $1 in
        --test)  Options_Test="yes"; shift;;  #// Without value
        -*) echo "Unknown option $1"; exit 1;;
        *) PositionalArgs+=("$1"); shift;;
    esac
done
set -- "${PositionalArgs[@]}"  #// set $1, $2, ...
unset PositionalArgs

function  Main() {
    local  workingFolderPath="${WorkingFolderPathDefault}"
    if [ ! -e "${workingFolderPath}/.codediff.ini" ]; then
        MakeWorkingFolderIfNot  "${workingFolderPath}"
        OpenIDE  "${workingFolderPath}"
    else
        ParseIniFile  "${workingFolderPath}/.codediff.ini"
        CreateWorkingFiles  0  "${workingFolderPath}/working_0"
        CreateWorkingFiles  1  "${workingFolderPath}/working_1"
        CreateNewGitWorking  "${workingFolderPath}/working_0"  "${workingFolderPath}/working_1"
        OpenIDE  "${workingFolderPath}/working"
    fi
}

function  MakeWorkingFolderIfNot() {
    local  workingFolderPath="$1"
    if [ ! -e "${workingFolderPath}" ]; then

        mkdir -p  "${workingFolderPath}"
    fi
    if [ ! -e "${workingFolderPath}/.codediff.ini" ]; then

        cp  "${ThisScriptParentPath}/codediff_template.ini"  "${workingFolderPath}/.codediff.ini"
    fi
}

function  CreateWorkingFiles() {
    local  index="$1"
    local  outputFolderPath="$2"
    local  settingName="${Setting_Name[${index}]}"
    local  localFullPath="${Setting_LocalFullPath[${index}]}"
    local  repositoryURL="${Setting_RepositoryURL[${index}]}"
    local  branchOrTag="${Setting_BranchOrTag[${index}]}"
    local  baseRelativePath="${Setting_BaseRelativePath[${index}]}"

    rm -rf  "${outputFolderPath}"
    if [ "${localFullPath}" != "" ]; then

        CopyFolder  "${localFullPath}"  "${outputFolderPath}"
    else
        local  options=""
        if [ "${branchOrTag}" != "" ]; then
            options="${options}  -b ${branchOrTag}"
        fi
        if [ "${baseRelativePath}" == "." ]; then

            git clone  "${repositoryURL}" ${options}  "${outputFolderPath}"  ||  Error
            rm -rf  "${outputFolderPath}/.git"
        elif [ "${baseRelativePath:0:2}" == ".." ]; then
            Error  "ERROR: BaseRelativePath cannot be set a parent folder."
        else
            git clone  --filter=blob:none --sparse  "${repositoryURL}" ${options} \
                "${WorkingFolderPathDefault}/workingOfWorking"  ||  Error
            pushd  "${WorkingFolderPathDefault}/workingOfWorking"  > /dev/null

            git sparse-checkout set "${baseRelativePath}"
            popd  > /dev/null
            rm -rf  "${outputFolderPath}"

            mv  "${WorkingFolderPathDefault}/workingOfWorking/${baseRelativePath}"  "${outputFolderPath}"
            rm -rf  "${WorkingFolderPathDefault}/workingOfWorking"
        fi
    fi
}

function  CreateNewGitWorking() {
    local  oldContentsPath="$1"
    local  newContentsPath="$2"
    AssertNotExist  "${oldContentsPath}/.git"
    AssertNotExist  "${newContentsPath}/.git"

    rm -rf "${workingFolderPath}/working"
    mkdir  "${workingFolderPath}/working"
    pushd  "${workingFolderPath}/working"  > /dev/null

    git init ${GitInitOption}  > /dev/null  2>&1
    git config --local user.email "you@example.com"
    git config --local user.name "Your Name"
    popd  > /dev/null
    mv  "${workingFolderPath}/working/.git"  "${oldContentsPath}"
    pushd  "${oldContentsPath}"  > /dev/null

    git add "."
    git commit -m "${Setting_Name[0]}"  > /dev/null  2>&1
    popd  > /dev/null
    mv  "${oldContentsPath}/.git"  "${newContentsPath}"
    pushd  "${newContentsPath}"  > /dev/null

    git add "."
    git commit -m "${Setting_Name[1]}"  > /dev/null  2>&1
    popd  > /dev/null
    mv  "${newContentsPath}/.git"  "${workingFolderPath}/working"
    pushd  "${workingFolderPath}/working"  > /dev/null

    git checkout "."  > /dev/null  2>&1
    git reset --soft HEAD^
    find "." -type f  |  xargs  -I {} \
        chmod 444 "{}"
    popd  > /dev/null
}

function  OpenIDE() {
    local  openingFolderPath="$1"
    if [ "${Options_Test}" != "" ]; then
        echo  "OpenIDE \"${openingFolderPath}\""  >  "_codediff.log"
    else
        echo  "codediff: \"${openingFolderPath}\""

        "${VisualStudioCodePath}" -g  "${openingFolderPath}"
    fi
}

function  ParseIniFile() {
    local  iniFilePath="$1"
    ResetSetting
    local  settingName=""
    local  localFullPath=""
    local  repositoryURL=""
    local  branchOrTag=""
    local  baseRelativePath=""
    AssertExist  "${iniFilePath}"

    local  settingIniFile="$( cat "${iniFilePath}" )"

    #// Read a setting .ini file
    local  oldIFS="$IFS"
    IFS=$'\n'
    local  settingIniFileLines=( ${settingIniFile} )
    IFS="$oldIFS"

    for  line  in "${settingIniFileLines[@]}"; do
        local  lineType="$( ParseIniFileLineType  "${line}" )"

        if [ "${lineType}" == "section" ]; then
            if [ "${settingName}" != "" ]; then
                AppendSetting  "${settingName}"  "${localFullPath}"  "${repositoryURL}"  "${branchOrTag}"  "${baseRelativePath}"
            fi

            settingName="$( ParseIniFileSectionName "${line}" )"
            localFullPath=""
            repositoryURL=""
            branchOrTag=""
            baseRelativePath=""
        elif [ "${lineType}" == "parameter" ]; then
            local  name="$( ParseIniFileParameterName  "${line}" )"
            local  value="$( ParseIniFileParameterValue  "${line}" )"
            value="$( Evaluate "${value}" )"
            if [ "${name}" == "LocalFullPath" ]; then
                localFullPath="${value}"
            elif [ "${name}" == "RepositoryURL" ]; then
                repositoryURL="${value}"
            elif [ "${name}" == "BranchOrTag" ]; then
                branchOrTag="${value}"
            elif [ "${name}" == "BaseRelativePath" ]; then
                baseRelativePath="${value}"
            else
                Error  "ERROR: Unknown parameter: ${name}."
            fi
        fi
    done
    AppendSetting  "${settingName}"  "${localFullPath}"  "${repositoryURL}"  "${branchOrTag}"  "${baseRelativePath}"

    if [ "${#Setting_Name[@]}" != 2 ]; then
        Error  "ERROR: section count must be 2 in ${workingFolderPath}/.codediff.ini file."
    fi
}

function  ResetSetting() {
    Setting_Name=( )
    Setting_LocalFullPath=( )
    Setting_RepositoryURL=( )
    Setting_BranchOrTag=( )
    Setting_BaseRelativePath=( )
}

function  AppendSetting() {
    local  settingName="$1"
    local  localFullPath="$2"
    local  repositoryURL="$3"
    local  branchOrTag="$4"
    local  baseRelativePath="$5"
    local  lastOfErrorMessage="in ${workingFolderPath}/.codediff.ini file."

    if [ "${settingName}" == "" ]; then
        Error  "ERROR: Not specified section name ${lastOfErrorMessage}"
    elif [ "${localFullPath}" != "" ]; then
        if [ "${localFullPath:0:1}" != "/" ]; then
            Error  "ERROR: LocalFullPath must be full path ${lastOfErrorMessage}"
        elif [ "${repositoryURL}" != "" ]; then
            Error  "ERROR: Cannot both setting LocalFullPath and RepositoryURL ${lastOfErrorMessage}"
        elif [ "${branchOrTag}" != "" ]; then
            Error  "ERROR: Cannot both setting LocalFullPath and BranchOrTag ${lastOfErrorMessage}"
        elif [ "${baseRelativePath}" != "" ]; then
            Error  "ERROR: Cannot both setting LocalFullPath and BaseRelativePath ${lastOfErrorMessage}"
        fi
    elif [ "${repositoryURL}" != "" ]; then
        if [ "${baseRelativePath}" == "" ]; then
            baseRelativePath="."
        fi
    else
        Error  "ERROR: LocalFullPath or RepositoryURL must be set ${lastOfErrorMessage}"
    fi

    Setting_Name+=("${settingName}")
    Setting_LocalFullPath+=("${localFullPath}")
    Setting_RepositoryURL+=("${repositoryURL}")
    Setting_BranchOrTag+=("${branchOrTag}")
    Setting_BaseRelativePath+=("${baseRelativePath}")
}

function  CopyFolder() {
    local  source="$1"
    local  destination="$2"
    local  ignoreDotGit="$3"  #// ${True}, ${False}(default)
    local  excludeOption="--exclude=./.git"
    source="$( CutLastOf  "${source}"  "/" )"
    destination="$( CutLastOf  "${destination}"  "/" )"
    if [ "${ignoreDotGit}" != ""  -a  "${ignoreDotGit}" != "${excludeOption}" ]; then
        TestError  "Bad option: ${ignoreDotGit}"
        return  "${False}"
    fi

    mkdir -p  "${destination}/"
    if [ "${ignoreDotGit}" == "${excludeOption}" ]; then
        ls -a "${source}" | grep -v  -e "^\.git$"  -e "^\.$"  -e "^\.\.$" | xargs  -I {} \
            cp -Rap  "${source}/{}"  "${destination}/"
    else
        ls -a "${source}" | grep -v  -e "^\.$"  -e "^\.\.$" | xargs  -I {} \
            cp -Rap  "${source}/{}"  "${destination}/"
    fi
}

function  CutLastOf() {
    local  wholeString="$1"
    local  lastExpected="$2"

    if [ "${wholeString:${#wholeString}-${#lastExpected}:${#lastExpected}}" == "${lastExpected}" ]; then
        echo  "${wholeString:0:${#wholeString}-${#lastExpected}}"
    else
        echo  "${wholeString}"
    fi
}

function  ParseIniFileLineType() {
    local  line="$1"
    local  words=$( echo "${line}" | xargs )
    local  head="${words:0:1}"

    if [ "${head}" == ""  -o  "${head}" == ";"  -o  "${head}" == "#" ]; then
        echo  "empty"
    elif [ "${head}" == "[" ]; then
        echo  "section"
    else
        echo  "parameter"
    fi
}

function  ParseIniFileSectionName() {
    local  line="$1"
    echo  "${line}"  |  sed -E 's/^\[|\] *$//g'
}

function  ParseIniFileParameterName() {
    local  line="$1"
    echo  "${line}"  |  grep -o  '[^ ]* *='  |  sed 's/ *=$//'
}

function  ParseIniFileParameterValue() {
    local  line="$1"
    local  quotedValue="$( echo "${line}"  |  grep -o  '".*"' )"
    if [ "${quotedValue}" != "" ]; then
        echo  "${quotedValue: 1 : $(( ${#quotedValue} - 2 ))}"  #// Cut " "
    else
        echo  "${line}"  |  grep -o '=.*'  |  sed -E 's/^= *//g'  
    fi
}

function  gitInitOption() {
    if [ "$( LessThanVersion "$(git --version)" "2.31.1" )" == "${True}" ]; then
        echo  ""
    else
        echo  "-bmain"  #// "-b main" occurs an error in bash debug
    fi
}

# LessThanVersion
#     if [ "$( LessThanVersion "$(git --version)" "2.31.1")" == "${True}" ]; then
function  LessThanVersion() {
    local  textContainsVersionA="$1"
    local  textContainsVersionB="$2"
    local  isGoodFormat="${True}"
    echo "${textContainsVersionA}" | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+" > /dev/null  ||  isGoodFormat="${False}"
    echo "${textContainsVersionB}" | grep -e "[0-9]\+\.[0-9]\+\.[0-9]\+" > /dev/null  ||  isGoodFormat="${False}"
    if [ "${isGoodFormat}" == "${False}" ]; then
        Error  "\"${textContainsVersionA}\" or \"${textContainsVersionB}\" is not semantic version."
    fi

    local  numbersA=( $( echo "${textContainsVersionA}" | grep -o -e "[0-9]\+" ) )
    local  numbersB=( $( echo "${textContainsVersionB}" | grep -o -e "[0-9]\+" ) )
    if [ "${numbersA[0]}" -lt "${numbersB[0]}" ]; then
        echo "${True}"
        return
    elif [ "${numbersA[0]}" == "${numbersB[0]}" ]; then
        if [ "${numbersA[1]}" -lt "${numbersB[1]}" ]; then
            echo "${True}"
            return
        elif [ "${numbersA[1]}" == "${numbersB[1]}" ]; then
            if [ "${numbersA[2]}" -lt "${numbersB[2]}" ]; then
                echo "${True}"
                return
            fi
        fi
    fi
    echo "${False}"
}

# Evaluate
#     Expand variables
# Example:
#     var1='value  1'
#     var2='${var1}  2'
#     evaluated="$( Evaluate "${var2}" )"  #// value  1  2
function  Evaluate() {
    local  expression="$1"
    eval echo "$( eval echo '\""${expression}"\"' )"
}

function  AssertExist() {
    local  path="$1"
    local  leftOfWildcard="${path%\**}"
    if [ "${leftOfWildcard}" == "${path}" ]; then  #// No wildcard

        if [ ! -e "${path}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    else
        local  rightOfWildcard="${path##*\*}"
        if [ ! -e "${leftOfWildcard}"*"${rightOfWildcard}" ]; then
            Error  "ERROR: Not found \"${path}\""
        fi
    fi
}

function  AssertNotExist() {
    local  path="$1"

    if [ -e "${path}" ]; then
        Error  "ERROR: Found \"${path}\""
    fi
}

function  Error() {
    local  errorMessage="$1"
    local  exitCode="$2"
    if [ "${errorMessage}" == "" ]; then
        errorMessage="ERROR"
    fi
    if [ "${exitCode}" == "" ]; then  exitCode=2  ;fi

    echo  "${errorMessage}" >&2
    exit  "${exitCode}"
}

True=0
False=1
GitInitOption=$(gitInitOption)
Setting_Name=( )
Setting_LocalFullPath=( )
Setting_RepositoryURL=( )
Setting_BranchOrTag=( )
Setting_BaseRelativePath=( )

Main
